name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose

    - name: Clippy (Linter)
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Rustfmt (Formatter)
      run: cargo fmt --check
