name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Triggers when you push tags like v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - aarch64-unknown-linux-gnu
          # Add more if needed

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Build using cross
      run: cross build --release --target ${{ matrix.target }}

    - name: Prepare binary for upload
      run: |
        BIN_NAME=Rudis
        EXT=""
        if [[ "${{ matrix.target }}" == *windows* ]]; then EXT=".exe"; fi

        mkdir -p dist
        cp target/${{ matrix.target }}/release/$BIN_NAME$EXT dist/${BIN_NAME}-${{ matrix.target }}$EXT
        cd dist
        zip ${BIN_NAME}-${{ matrix.target }}.zip ${BIN_NAME}-${{ matrix.target }}$EXT

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
